### ISSUE TITLE
Datasets used in the demo script

### ISSUE THREAD

**Issue by manner** [Stream-AD/MStream#3]
We're currently porting and integrating MStream to the online machine learning framework [river](https://github.com/online-ml/river) and were trying to reproduce the results with the given datasets. Unfortunately, the `run.sh` script doesn't work out of the box but requires preprocessed variants of the used datasets, which are split up into categorical, numerical, and timestamp parts. Do you have those preprocessed files available somewhere?

**Comment by bhatiasiddharth** [comment]
Thank you for your interest in integrating MStream into river. Sharing the processed datasets over email.
